blog-web-app/Controllers/AdminController.cs
using blog_web_app.Models;
using blog_web_app.Services;
using blog_web_app.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace blog_web_app.Controllers;

[Authorize]
public class AdminController : Controller
{
    private readonly IArticleService _articleService;
    private readonly ICategoryService _categoryService;
    
    public AdminController(IArticleService articleService, ICategoryService categoryService)
    {
        _articleService = articleService;
        _categoryService = categoryService;
    }

    public IActionResult Articles() => View(_articleService.Articles);
    
    public IActionResult Categories() => View(_categoryService.Categories);

    [HttpGet]
    public async Task<IActionResult> EditArticle(Guid? id)
    {
        if (id == null) 
            return NotFound();
        
        var article = await _articleService.GetByIdAsync(id);
        if (article == null)
            return NotFound();

        var model = new ArticleViewModel
        {
            Article = article,
            Categories = _categoryService.Categories
        };

        return View(model);
    }
    
    [HttpPost]
    public async Task<IActionResult> EditArticle(ArticleViewModel model, IFormFile? image = null)
    {
        if (!ModelState.IsValid)
        {
            model.Categories = _categoryService.Categories;
            return View(model);
        }

        var article = await _articleService.GetByIdAsync(model.Article.Id);
        if (article == null) 
            return View(model);
        
        article.Name = model.Article.Name;
        article.ShortDescription = model.Article.ShortDescription;
        article.Description = model.Article.Description;
        article.CategoryId = model.Article.CategoryId;
        
        if (image != null)
        {
            using (var binaryReader = new BinaryReader(image.OpenReadStream()))
            {
                article.ImageData = binaryReader.ReadBytes((int)image.Length);
            }
        }
        
        await _articleService.UpdateAsync(article);
        return RedirectToAction("Articles");
    }
    
    [HttpGet]
    public async Task<IActionResult> EditCategory(Guid? id)
    {
        if (id == null) 
            return NotFound();
        
        var category = await _categoryService.GetByIdAsync(id);
        if (category == null)
            return NotFound();
            
        var model = new Category
        {
            Id = category.Id, Name = category.Name
        };
        
        return View(model);
    }
    
    [HttpPost]
    public async Task<IActionResult> EditCategory(Category model)
    {
        if (!ModelState.IsValid) 
            return View(model);
        
        var category = await _categoryService.GetByIdAsync(model.Id);
        if (category == null) 
            return View(model);
        
        category.Name = model.Name;
        
        await _categoryService.UpdateAsync(category);
        return RedirectToAction("Categories");
    }

    [HttpGet]
    public IActionResult CreateArticle()
    {
        var model = new ArticleViewModel
        {
            Article = new(),
            Categories = _categoryService.Categories
        };
        return View("CreateArticle", model);
    }

    [HttpPost]
    public async Task<IActionResult> CreateArticle(ArticleViewModel model, IFormFile? image = null)
    {
        if (!ModelState.IsValid)
        {
            model.Categories = _categoryService.Categories;
            return View(model);
        }

        var article = model.Article;
        if (image != null)
        {
            using (var binaryReader = new BinaryReader(image.OpenReadStream()))
            {
                article.ImageData = binaryReader.ReadBytes((int)image.Length);
            }
        }
        
        await _articleService.AddAsync(article);
        return RedirectToAction("Articles");
    }

    [HttpGet]
    public IActionResult CreateCategory() => View();

    [HttpPost]
    public async Task<IActionResult> CreateCategory(Category model)
    {
        if (!ModelState.IsValid) 
            return View(model);
        
        await _categoryService.AddAsync(model);
        return RedirectToAction("Categories");
    }
    
    [HttpPost]
    public async Task<IActionResult> DeleteArticle(Guid? id)
    {
        if (id == null) return NotFound();
        await _articleService.DeleteAsync(id);
        return RedirectToAction("Articles");
    }
    
    [HttpPost]
    public async Task<IActionResult> DeleteCategory(Guid? id)
    {
        if (id == null) return NotFound();
        var category = _categoryService.GetByIdAsync(id).Result;
        if (!_articleService.Articles.Any(a => a.CategoryId == id))
        {
            TempData["success-message"] = $"Категория \"{category?.Name}\" успешно удалена";
            await _categoryService.DeleteAsync(id);
        }
        else
        {
            TempData["error-message"] = $"Категория \"{category?.Name}\" относится к одной или более статьям и не может быть удалена";
        }
        return RedirectToAction("Categories");
    }
}

blog-web-app/Controllers/ArticleController.cs
using System.Diagnostics;
using blog_web_app.Models;
using blog_web_app.Services;
using blog_web_app.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace blog_web_app.Controllers;

public class ArticleController : Controller
{
    private readonly IArticleService _articleService;
    private readonly ICategoryService _categoryService;

    public ArticleController(IArticleService articleService, ICategoryService categoryService)
    {
        _articleService = articleService;
        _categoryService = categoryService;
    }

    public IActionResult List(ArticleSearchViewModel searchViewModel, int currentPage = 1)
    {
        var categories = _categoryService.Categories.ToList();
        categories.Insert(0, new Category { Id = Guid.Empty, Name = "Все" });
        
        int pageSize = 3;

        var articles = searchViewModel.CategoryId != null && searchViewModel.CategoryId != Guid.Empty
            ? _articleService.Articles
                .Where(a => a.CategoryId == searchViewModel.CategoryId)
            : _articleService.Articles;

        if (searchViewModel.StartDate != null && searchViewModel.EndDate != null)
        {
            articles = articles.Where(a => a.CreationDate.Date >= searchViewModel.StartDate
                                                && a.CreationDate.Date <= searchViewModel.EndDate);
        }
        
        var count = articles.Count();
        var pageViewModel = new PageViewModel(count, currentPage, pageSize);
        
        var model = new ArticleListViewModel
        {
            SearchViewModel = new ArticleSearchViewModel { Categories = categories.AsQueryable() },
            Articles = articles.Skip((currentPage - 1) * pageSize).Take(pageSize),
            PageViewModel = pageViewModel
        };

        return View(model);
    }

    public async Task<IActionResult> ArticleInfo(Guid id)
    {
        var model = await _articleService.GetByIdAsync(id);
        if(model != null)
        {
            var category = _categoryService.GetByIdAsync(model.CategoryId).Result;
            ViewBag.Category = category == null ? "не указано" : category.Name;
        }

        return View(model);
    }
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

blog-web-app/Views/Shared/ArticleBriefInfo.cshtml
@model Article

<div class="col-sm-6 col-md-4">
    <div class="card">
        <div class="card h-100">
            @if (Model.ImageData != null)
            {
                <img class="card-img-top" src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.ImageData))" alt="...">
            }
            else
            {
                <img class="card-img-top" src="https://fomantic-ui.com/images/wireframe/image.png" alt="...">
            }
            <div class="card-body">
                <h3 class="card-title">@Model.Name</h3>
                <p class="card-text">@Model.ShortDescription</p>
                <p>
                    <a asp-controller="Article" asp-action="ArticleInfo" asp-route-id="@Model.Id" class="btn btn-dark" role="button">Читать статью</a>
                </p>
            </div>
        </div>
    </div>
</div>

blog-web-app/Views/Shared/ArticleInfo.cshtml
@model Article

<div class="col-sm-6 col-md-4">
    <div class="card">
        <div class="card h-100">
            <img class="card-img-top" src="https://s1.1zoom.ru/big7/888/Eyes_Owls_Bubo_502568.jpg" alt="...">
            <div class="card-body">
                <h3 class="card-title">@Model.Name</h3>
                <p class="card-text">@Model.ShortDescription</p>
                <p>
                    <a asp-controller="Article" asp-action="Index" asp-route-id="@Model.Id" class="btn btn-dark" role="button">Читать статью</a>
                </p>
            </div>
        </div>
    </div>
</div>

blog-web-app/Views/Shared/Pagination.cshtml
@model blog_web_app.ViewModels.PageViewModel

@if (Model.HasPreviousPage)
{
    <a asp-action="List" asp-route-currentPage="@(Model.CurrentPageNumber - 1)" class="btn btn-outline-dark">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Назад
    </a>
}
@if (Model.HasNextPage)
{
    <a asp-action="List" asp-route-currentPage="@(Model.CurrentPageNumber + 1)" class="btn btn-outline-dark">
        Вперед
        <i class="glyphicon glyphicon-chevron-right"></i>
    </a>
}

blog-web-app/Views/Shared/SearchForm.cshtml
@model blog_web_app.ViewModels.ArticleSearchViewModel

<form class="form-inline">
    <label>Выберите категорию:</label>
    <select asp-for="CategoryId" class="form-control">
        @foreach(var category in Model.Categories)
        {
            <option value="@category.Id">@category.Name</option>
        }
    </select>
    <input class="form-control" type="date" date-val="true" asp-for="StartDate" value="@DateTime.UtcNow.ToString("yyyy-MM-dd")">
    <input class="form-control" type="date" date-val="true" asp-for="EndDate" value="@DateTime.UtcNow.ToString("yyyy-MM-dd")">
    <button class="btn btn-dark" type="submit">Поиск</button>
</form>

blog-web-app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - blog_web_app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/blog_web_app.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Article" asp-action="List">blog_web_app</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="List">Главная</a>
                    </li>
                    @if(User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Articles">Статьи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Categories">Категории</a>
                        </li>
                        <li class="nav-item" style="margin-left: auto; margin-right: 0">
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <button type="submit" class="btn btn-dark">Выход</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item" style="margin-left: auto; margin-right: 0">
                            <a class="btn btn-dark" asp-area="" asp-controller="Account" asp-action="Login">Вход</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; @DateTime.Today.Year - blog_web_app
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>